const abilityCards = [
  { category: '📖學習成長能力', title: '🚀快速學習者', description: '能快速掌握陌生主題並應用在實際任務中' },
  { category: '📖學習成長能力', title: '🔦知識搜尋者', description: '擅長查找資訊與資源，快速取得所需答案'},
  { category: '📖學習成長能力', title: '📅自主學習者', description: '有計劃地學習新技能，並持續自我精進'},
  { category: '📖學習成長能力', title: '🧗思考整合者', description: '能統整不同觀點或資訊，轉化為清楚架構'},
  { category: '📖學習成長能力', title: '🌌好奇探索者', description: '喜歡探究未知領域，主動延伸學習內容'},
  { category: '📖學習成長能力', title: '🔁回饋吸收者', description: '能從他人建議中進行調整與成長'},
  { category: '📖學習成長能力', title: '🍽️概念消化者', description: '能理解抽象概念，轉換為具體應用'},
  { category: '📖學習成長能力', title: '⏫持續進步者', description: '樂於設定個人成長目標，持續追求進步'},

  { category: '📅自我管理能力', title: '⏰時間管理者', description: '懂得安排時間與優先順序，任務執行有效率'},
  { category: '📅自我管理能力', title: '📆習慣建立者', description: '能養成良好習慣並維持穩定的日常節奏'},
  { category: '📅自我管理能力', title: '🧘壓力調節者', description: '在壓力下保持冷靜，處事不慌亂'},
  { category: '📅自我管理能力', title: '🏁自我激勵者', description: '能自行設定目標並持續行動，不依賴外部動機'},
  { category: '📅自我管理能力', title: '🧾任務執行者', description: '能確實執行計畫，完成分配的任務'},
  { category: '📅自我管理能力', title: '📏紀律實踐者', description: '能遵守規範與原則，維持高度自律'},
  { category: '📅自我管理能力', title: '🌊情緒穩定者', description: '面對挑戰與衝突時保持理性與穩定表現'},
  { category: '📅自我管理能力', title: '🔄反思調整者', description: '能檢討過往行為並做出具體改進'},

  { category: '💬溝通表達能力', title: '🗣️表達清晰者', description: '能清楚說明想法，讓他人容易理解'},
  { category: '💬溝通表達能力', title: '🧠說服影響者', description: '能運用語言與邏輯影響他人接受觀點'},
  { category: '💬溝通表達能力', title: '🦱傾聽理解者', description: '能專注傾聽並理解他人真正需求'},
  { category: '💬溝通表達能力', title: '💞共感傳達者', description: '擅長用對方能接受的方式表達想法'},
  { category: '💬溝通表達能力', title: '🖋書寫表達者', description: '能寫出通順、有邏輯的文章或文字內容'},
  { category: '💬溝通表達能力', title: '🎨視覺溝通者', description: '能利用圖表、設計或簡報輔助表達重點'},
  { category: '💬溝通表達能力', title: '🗺️多語能力者', description: '使用英語或外語的溝通能力'},
  { category: '💬溝通表達能力', title: '🪢溝通協調者', description: '在意見不合時能促進理解與化解衝突'},

  { category: '🤝人際關係能力', title: '🤗信任建立者', description: '能與不同背景的人建立信任關係'},
  { category: '🤝人際關係能力', title: '🌱關係經營者', description: '經常主動關心他人，維持良好互動'},
  { category: '🤝人際關係能力', title: '🎭情緒覺察者', description: '能察覺他人情緒變化並做出適當回應'},
  { category: '🤝人際關係能力', title: '🔧合作協調者', description: '能在多人互動中維持和諧氣氛，減少摩擦'},
  { category: '🤝人際關係能力', title: '🕸人脈連結者', description: '有能力建立人脈網絡，必要時能找到人幫忙'},
  { category: '🤝人際關係能力', title: '🍀社交主動者', description: '主動參與社交場合，積極認識新朋友'},
  { category: '🤝人際關係能力', title: '🌀因人應變者', description: '面對不同個性的人能調整溝通或互動方式'},
  { category: '🤝人際關係能力', title: '🏘️團體歸屬者', description: '能融入團體文化並為成員帶來安全感'},

  { category: '🧑‍🤝‍🧑團隊合作能力', title: '📦分工協作者', description: '能在團隊中分擔任務，並協調資源與時間'},
  { category: '🧑‍🤝‍🧑團隊合作能力', title: '📣團隊凝聚者', description: '能鼓舞團隊士氣並促進成員彼此合作'},
  { category: '🧑‍🤝‍🧑團隊合作能力', title: '🧯支援補位者', description: '願意支援他人工作，協助解決突發問題'},
  { category: '🧑‍🤝‍🧑團隊合作能力', title: '🎚角色適應者', description: '能依團隊需要轉換領導、協調、執行等角色'},
  { category: '🧑‍🤝‍🧑團隊合作能力', title: '🧩意見整合者', description: '能統整不同想法，協助形成共識'},
  { category: '🧑‍🤝‍🧑團隊合作能力', title: '📋決策配合者', description: '即使不同意，也能配合團隊決議執行任務'},
  { category: '🧑‍🤝‍🧑團隊合作能力', title: '🔈團隊溝通者', description: '能讓資訊清楚傳遞給團隊所有成員'},
  { category: '🧑‍🤝‍🧑團隊合作能力', title: '🎯任務導向者', description: '注重團隊目標，確保工作進展與結果'},

  { category: '🧩問題解決能力', title: '🔬問題拆解者', description: '能將複雜問題分解為可處理的小部分' },
  { category: '🧩問題解決能力', title: '🕵原因追查者', description: '擅長找出問題背後真正原因' },
  { category: '🧩問題解決能力', title: '🗡️決策行動者', description: '能清楚明快地做出決定並執行' },
  { category: '🧩問題解決能力', title: '🌈創意解方者', description: '能從不同角度提出具創意的解決方案' },
  { category: '🧩問題解決能力', title: '⚖️分析判斷者', description: '能評估各種方案的優劣並做出判斷' },
  { category: '🧩問題解決能力', title: '🚧解決實踐者', description: '願意採取行動並測試解決方法的成效' },
  { category: '🧩問題解決能力', title: '🛡️危機處理者', description: '面對突發狀況能迅速應對並穩住局面' },
  { category: '🧩問題解決能力', title: '🌐系統思考者', description: '能從整體脈絡分析問題，不只看表面現象' },

  { category: '💡創新思維能力', title: '💭創新發想者', description: '常能產生新點子並提出與眾不同的構想' },
  { category: '💡創新思維能力', title: '🧨挑戰現狀者', description: '喜歡質疑慣例流程，尋找更好的做法' },
  { category: '💡創新思維能力', title: '🪄概念重組者', description: '能結合不同領域的知識創造新想法' },
  { category: '💡創新思維能力', title: '🏗️嘗試行動者', description: '願意嘗試沒做過的方法，不怕失敗' },
  { category: '💡創新思維能力', title: '🦉開放接受者', description: '願意接受不同觀點與刺激，拓展思考可能' },
  { category: '💡創新思維能力', title: '👁多角觀察者', description: '觀察問題的角度多元，不拘泥單一思維模式' },
  { category: '💡創新思維能力', title: '🦋改變倡議者', description: '能主動提出改善建議並推動變革' },
  { category: '💡創新思維能力', title: '🌀創意思考者', description: '善於運用隱喻、類比等技巧激發創造力' },

  { category: '💻數位應用能力', title: '🛠數位工具者', description: '熟悉常見辦公與線上協作工具' },
  { category: '💻數位應用能力', title: '📚資訊統整者', description: '能有效彙整與整理網路或平台上的資訊內容' },
  { category: '💻數位應用能力', title: '📊資料處理者', description: '能使用表格、統計或簡易資料分析工具處理資訊' },
  { category: '💻數位應用能力', title: '🎥視覺製作者', description: '能製作簡報、圖像或影片傳達訊息' },
  { category: '💻數位應用能力', title: '🧮系統操作者', description: '能快速學會新系統或平台的操作方式' },
  { category: '💻數位應用能力', title: '📢自媒運用者', description: '能經營個人品牌或內容於社群平台' },
  { category: '💻數位應用能力', title: '🧑‍💻數位整合者', description: '能整合多種數位工具提升工作或學習效率' },
  { category: '💻數位應用能力', title: '🤖程式理解者', description: '了解基本程式邏輯，能協助簡易自動化或串接應用' }
];
